### ISSUE TITLE
2020年3月11日 ndxbn's ToDo

### ISSUE THREAD

**Issue by ndxbn** [sanabutton/sanabutton.github.io#598]
- [x] https://github.com/sanabutton/frontend/pull/94 のマージ
- [x] close https://github.com/sanabutton/sanabutton.github.io/issues/575
- [x] make GitHub Release on https://github.com/sanabutton/frontend/pull/94
- [x] make long TTL to devel.natorisana.love domain; now it's 60s as short as debugging and quality testing.

**Comment by ndxbn** [comment]
https://github.com/sanabutton/frontend/releases/tag/0.1.0
